### ISSUE TITLE
Not compatible with chai 2.0.0 ?

### ISSUE THREAD

**Issue by Koblaid** [michelsalib/chai-shallow-deep-equal#8]
npm reports an error when I try to install chai-shallow-deep-equal with chai 2.0.0

It seems this is configured in package.json:

```
"peerDependencies": {
        "chai": ">= 1.9.0 < 2"
    },
```

Is there a specific reason for the dependency to be ``` < 2 ```? Could this restriction be removed?

**Comment by michelsalib** [comment]
That's because increasing the major version theoretically means "breaking change in the interface". This is why we lock the plugin to work on the current version of the interface of chai (was 1.x.x at the time).
So we should run some test and ensure it still works with chai 2.x.x and I'll gladly remove this limitation.
